/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : mosmann
 * Created : 06/22/2014 07:46:59
 */
package de.flapdoodle.soapy.config;

import java.util.List;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.Lists;

public class MethodAliasBuilder {
    private Name<MethodAlias> name;
    private Name<Method> sourceMethod;
    private final List<TypeAlias> types=Lists.newArrayList();

    public MethodAliasBuilder name(String name) {
        this.name = Name.of(MethodAlias.class, name);
        return this;
    }

    public MethodAliasBuilder sourceMethod(Name<Method> sourceMethod) {
        this.sourceMethod = sourceMethod;
        return this;
    }

    public MethodAliasBuilder type(TypeAlias type) {
        this.types.add(type);
        return this;
    }

    public MethodAlias build() {
        return new MethodAlias(name, sourceMethod, ImmutableList.copyOf(types));
    }
}