/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : mosmann
 * Created : 06/22/2014 07:26:22
 */
package de.flapdoodle.soapy.config;

public class MethodBuilder {
    private Name<Method> name;
    private Name<Type> response;
    private Name<Type> request;

    public MethodBuilder name(String name) {
        this.name = Name.of(Method.class, name);
        return this;
    }

    public MethodBuilder response(Name<Type> response) {
        this.response = response;
        return this;
    }

    public MethodBuilder request(Name<Type> request) {
        this.request = request;
        return this;
    }

    public Method build() {
        return new Method(name, response, request);
    }
}