/**
 * Copyright (C) 2013
 *   Michael Mosmann <michael@mosmann.de>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : mosmann
 * Created : 06/22/2014 07:26:22
 */
package de.flapdoodle.soapy.config;

public class MethodBuilder {
    private Name<Method> name;
    private Name<Type> response;
    private Name<Type> request;

    public MethodBuilder name(String name) {
        this.name = Name.of(Method.class, name);
        return this;
    }

    public MethodBuilder response(Name<Type> response) {
        this.response = response;
        return this;
    }

    public MethodBuilder request(Name<Type> request) {
        this.request = request;
        return this;
    }

    public Method build() {
        return new Method(name, response, request);
    }
}