/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : mosmann
 * Created : 06/22/2014 07:48:47
 */
package de.flapdoodle.soapy.config;


public class PropertyAliasBuilder {
    private Name<PropertyAlias> name;
    private Name<Property> sourceProperty;

    public PropertyAliasBuilder name(String name) {
        this.name = Name.of(PropertyAlias.class, name);
        return this;
    }

    public PropertyAliasBuilder sourceProperty(Name<Property> sourceProperty) {
        this.sourceProperty = sourceProperty;
        return this;
    }

    public PropertyAlias build() {
        return new PropertyAlias(name, sourceProperty);
    }
}