/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : mosmann
 * Created : 06/22/2014 07:49:22
 */
package de.flapdoodle.soapy.config;

import java.util.List;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.Lists;

public class ServiceAliasBuilder {
    private Name<ServiceAlias> name;
    private Name<Service> sourceService;
    private final List<MethodAlias> methods=Lists.newArrayList();

    public ServiceAliasBuilder name(String name) {
        this.name = Name.of(ServiceAlias.class, name);
        return this;
    }

    public ServiceAliasBuilder sourceService(Name<Service> sourceService) {
        this.sourceService = sourceService;
        return this;
    }

    public ServiceAliasBuilder methods(MethodAlias method) {
        this.methods.add(method);
        return this;
    }

    public ServiceAlias build() {
        return new ServiceAlias(name, sourceService, ImmutableList.copyOf(methods));
    }
}