/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : mosmann
 * Created : 06/22/2014 07:27:01
 */
package de.flapdoodle.soapy.config;

import java.util.List;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.Lists;

public class ServiceBuilder {
    private Name<Service> name;
    private final List<Method> methods=Lists.newArrayList();

    public ServiceBuilder name(String name) {
        this.name = Name.of(Service.class, name);
        return this;
    }
    
    
    public ServiceBuilder method(Method method) {
        this.methods.add(method);
        return this;
    }

    public Service build() {
        return new Service(name, ImmutableList.copyOf(methods));
    }
}