/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : mosmann
 * Created : 06/22/2014 07:51:08
 */
package de.flapdoodle.soapy.config;

import java.util.List;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.Lists;

public class TypeAliasBuilder {
    private Name<TypeAlias> name;
    private Name<Type> sourceType;
    private final List<PropertyAlias> properties=Lists.newArrayList();

    public TypeAliasBuilder name(String name) {
        this.name = Name.of(TypeAlias.class, name);
        return this;
    }

    public TypeAliasBuilder sourceType(Name<Type> sourceType) {
        this.sourceType = sourceType;
        return this;
    }

    public TypeAliasBuilder property(PropertyAlias property) {
        this.properties.add(property);
        return this;
    }

    public TypeAlias build() {
        return new TypeAlias(name, sourceType, ImmutableList.copyOf(properties));
    }
}