/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : mosmann
 * Created : 06/22/2014 07:28:43
 */
package de.flapdoodle.soapy.config;

import java.util.List;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.Lists;

public class TypeBuilder {
    private Name<Type> name;
    private final List<Name<Type>> baseTypes=Lists.newArrayList();
    private final List<Property> properties=Lists.newArrayList();

    public TypeBuilder name(String name) {
        this.name = Name.of(Type.class,name);
        return this;
    }

    public TypeBuilder baseType(Name<Type> baseType) {
        this.baseTypes.add(baseType);
        return this;
    }

    public TypeBuilder property(Property property) {
        this.properties.add(property);
        return this;
    }

    public Type build() {
        return new Type(name, ImmutableList.copyOf(baseTypes), ImmutableList.copyOf(properties));
    }
}